# Lower RAM allocation to prevent Windows from killing the build process
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m

# Re-enable daemon so builds compile faster without launching a new JVM every time
org.gradle.daemon=true
org.gradle.parallel=true

android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false