// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//MICO GENTIL
//25094130
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpuN9dOdsY0f3ALETxkKAHK1oX9e46Ko',
    appId: '1:898363854760:web:70ab03086d3aac3601179d',
    messagingSenderId: '898363854760',
    projectId: 'social-media-app-auth-39e38',
    authDomain: 'social-media-app-auth-39e38.firebaseapp.com',
    storageBucket: 'social-media-app-auth-39e38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRTNcZGn0gl29xIVBXz3CqdvOTTKVosU',
    appId: '1:898363854760:android:91cf537a14d9ff1601179d',
    messagingSenderId: '898363854760',
    projectId: 'social-media-app-auth-39e38',
    storageBucket: 'social-media-app-auth-39e38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtQnNtznJ54a_k71_V0SvpIfy1se8ODI',
    appId: '1:898363854760:ios:5e2d7fc34b3a1c5b01179d',
    messagingSenderId: '898363854760',
    projectId: 'social-media-app-auth-39e38',
    storageBucket: 'social-media-app-auth-39e38.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvtQnNtznJ54a_k71_V0SvpIfy1se8ODI',
    appId: '1:898363854760:ios:5e2d7fc34b3a1c5b01179d',
    messagingSenderId: '898363854760',
    projectId: 'social-media-app-auth-39e38',
    storageBucket: 'social-media-app-auth-39e38.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGpuN9dOdsY0f3ALETxkKAHK1oX9e46Ko',
    appId: '1:898363854760:web:230bb4910654cf8501179d',
    messagingSenderId: '898363854760',
    projectId: 'social-media-app-auth-39e38',
    authDomain: 'social-media-app-auth-39e38.firebaseapp.com',
    storageBucket: 'social-media-app-auth-39e38.firebasestorage.app',
  );
}
